In [1]:
import pandas as pd

In [2]:
raw_data=pd.read_csv('Dataset_feuilles_1.csv')

In [3]:
raw_data.head()

,id,species,margin1,margin2,margin3,margin4,margin5,margin6,margin7,margin8,...,texture55,texture56,texture57,texture58,texture59,texture60,texture61,texture62,texture63,texture64
0,1,Acer_Opalus,0.007812,0.023438,0.023438,0.003906,0.011719,0.009766,0.027344,0.0,...,0.007812,0.000000,0.002930,0.002930,0.035156,0.0,0.0,0.004883,0.000000,0.025391
1,2,Pterocarya_Stenoptera,0.005859,0.000000,0.031250,0.015625,0.025391,0.001953,0.019531,0.0,...,0.000977,0.000000,0.000000,0.000977,0.023438,0.0,0.0,0.000977,0.039062,0.022461
2,3,Quercus_Hartwissiana,0.005859,0.009766,0.019531,0.007812,0.003906,0.005859,0.068359,0.0,...,0.154300,0.000000,0.005859,0.000977,0.007812,0.0,0.0,0.000000,0.020508,0.002930
3,5,Tilia_Tomentosa,0.000000,0.003906,0.023438,0.005859,0.021484,0.019531,0.023438,0.0,...,0.000000,0.000977,0.000000,0.000000,0.020508,0.0,0.0,0.017578,0.000000,0.047852
4,6,Quercus_Variabilis,0.005859,0.003906,0.048828,0.009766,0.013672,0.015625,0.005859,0.0,...,0.096680,0.000000,0.021484,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.031250

In [4]:
from sklearn.preprocessing import LabelEncoder
labelencoder=LabelEncoder()

for col in raw_data.columns:
    raw_data[col]=labelencoder.fit_transform(raw_data[col])

In [12]:
X=raw_data.iloc[:,2:194]
y=raw_data.iloc[:,1]

In [13]:
X.head()

,margin1,margin2,margin3,margin4,margin5,margin6,margin7,margin8,margin9,margin10,...,texture55,texture56,texture57,texture58,texture59,texture60,texture61,texture62,texture63,texture64
0,4,12,12,2,6,5,14,0,1,17,...,8,0,3,3,36,0,0,5,0,26
1,3,0,16,8,13,1,10,0,0,4,...,1,0,0,1,24,0,0,1,40,23
2,3,5,10,4,2,3,35,0,0,23,...,128,0,6,1,8,0,0,0,21,3
3,0,2,12,3,11,10,12,0,7,9,...,0,1,0,0,21,0,0,18,0,49
4,3,2,25,5,7,8,3,0,0,3,...,90,0,22,0,0,0,0,0,0,32

In [14]:
y.head()

0     3
1    49
2    65
3    94
4    84
Name: species, dtype: int64

In [15]:
#from sklearn.preprocessing import label_binarize 
#y = label_binarize(y, classes=[0, 1, 2, 3,4])

In [16]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [26]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()

y_score=lr.fit(X_train,y_train).decision_function(X_test)[:,2]

In [27]:
from sklearn import metrics
n_classes=5
# Compute ROC curve and ROC area for each class
fpr = dict()
tpr = dict()
roc_auc = dict()
for i in range(n_classes):
    fpr[i], tpr[i], _ = metrics.roc_curve(y_test[:, i], y_score[:, i])
    roc_auc[i] = auc(fpr[i], tpr[i])

ValueError: Can only tuple-index with a MultiIndex

In [ ]:
from sklearn import metrics
y_prob=lr.predict_proba(X_test)[:,2]
[fpr,tpr,thr]=metrics.roc_curve(y_test,y_prob)

In [ ]:
fpr
thr
tpr

In [ ]:
import matplotlib.pyplot as plt
plt.plot(fpr,tpr,color='red')
plt.plot([0,1],[0,1],linestyle='--')
plt.show